import "./globals.css";
import "remixicon/fonts/remixicon.css";
import Header from "@/components/organisms/header";
import { montserrat, poppins } from "./fonts";

export const metadata = {
  title: "HANAJEONG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${poppins.variable} ${montserrat.variable}`}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
